[package]
name = "ptero-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Clap command tree for Pterodactyl CLI"

[dependencies]
ptero-protocol = { workspace = true }
ptero-config = { workspace = true }
ptero-core = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
